### PR TITLE
Adds info about PyPi

### PR DESCRIPTION
**Pull request by mlissner**
It'd be nice to have more detail here, but this helps a little at least.

### CODE REVIEW

**Comment by mlissner** [comment]
So changed!

**Comment by graingert** [comment]
Nice, can you squash and update your commit message

**Comment by mlissner** [comment]
Actually, I don't know how to do that, but you can do it when you do the merge, right? I'm just working with the github website here...

**Comment by graingert** [comment]
Sure, but I don't think I can rename commits from the gui. I'll do it when I get to a keyboard.

As an aside you can also use https://try.github.io/ to get the basics of using git

**Comment by mlissner** [comment]
Hey - just realizing that this PR never got merged b/c of some bad git-fu on my behalf. Is it still worth merging?

**Comment by graingert** [comment]
Can you squash your commits and use the message "add installation instructions"

**Comment by mlissner** [comment]
Sorry, I honestly don't know how to do that, and I don't care to learn. I've got too much in my head already. I guess this PR is a no-go. Too bad, closing.

**Pull request closed without merging**
